### ISSUE TITLE
Intersect Town Hall  - 25th June 2024 - Summaries and tracking

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#2]
- [ ] @stephen-rowan to transfer summary content to GitBook
- [x] Consider how to extrapolate thinking
- [x] Review previous TH summary at WG 1 planning meeting each month ?

Summaries and tracking for monthly TH sessions

## Relevant Proposal text

- https://catalyst-swarm.gitbook.io/intersect-town-hall-playbook/the-proposal/intersect-town-hall-by-swarm

> Facilitating monthly Intersect Town Hall: 8 monthly Town Halls, beginning in June and ending in December 2024
This task is intended to

### Deliverable

- https://catalyst-swarm.gitbook.io/intersect-town-hall-playbook/the-proposal/intersect-town-hall-by-swarm
- draft on Google Doc: https://docs.google.com/document/d/1NapqwCi0K1P57RjNjLffrLQg0w6RkQ6BJvhM-68B7M0
Session Slides: [Intersect TH slides 25th June 2024](https://docs.google.com/presentation/d/1c-UQtW_Jdm5TPjgVScJFzQdEnRrbQn7TAucGm9LzBOw/edit#slide=id.g2e81879d9ac_0_86)
- Youtube Video Links:
Intersect https://www.youtube.com/watch?v=GPGOjeH_Wkg
Swarm https://youtu.be/kN17feSQnVQ

- The tracking is addressed currently by importing Zoom participation data to Swarm Treasury System. Currently no public link has been created, the tracking results will included in the Q3 report

> 

### Acceptance Criteria

>.

### Estimated Duration 

>

### Cost

>

## Meeting Summary

Hosts:
Tevo Saks - Swarm Veteran - Swarm
Vanessa Cardui - Swarm Veteran - Swarm

Co-Hosts:
Lara [?] - [position?] - Intersect
Abhig [?] - [position?] - Intersect
Felix Weber - Swarm Veteran - Swarm
Stephen Whitenstall - Swarm Veteran - Swarm

We kicked off Intersect Town Hall with a welcome to Intersect and our Town Hall structure, which includes the idea of After Town Halls and how to engage.

After that, we proceed to cover different types of updates and topics:

- Town Hall regular experiments will introduce voting in the Town Halls.

Here is an opportunity to suggest topics via this Zoom survey: https://s.zoom.us/m/bZlnuX4KX

- Vani shared the Community Problem Board, explaining its purpose and how it can be used by the community. https://github.com/orgs/Catalyst-Swarm/projects/2/views/1

It is for identifying Community Problems and distilling them into smaller subjects. Once pattern emerge it will be easier to prioritize them
Problem Stages: Problem is Identified > Problem is being defined > Problem is being worked on > problem needs redefining > problem is fixed

- Tevo provided updates on the Interim Constitution committees, mentioning the upcoming results and ways to read up on it

“Constitution serves as a guiding set of principles for the operation and governance of our collective efforts, fostering an environment where all participants can contribute to the betterment of the Cardano Blockchain ecosystem as a whole.”

The Council will comprise seven full members and three alternates, who will be required to sign and abide by the terms of the Intersect Constitutional Charter.
Currently people can apply to be part of Constitutional Council, deadline is 1st July

Application link: https://docs.google.com/forms/d/e/1FAIpQLScGLyp73xO4u1dZtjLgCuY1JEqSqkN1vtlaDn1s1Yiny6CJVw/viewform
Portal: https://constitution.gov.tools/en/interim-constitution
GPT: https://chatgpt.com/g/g-6NEy1e4rb-cardano-interim-constitution-gpt

- Vani announced that future Town Halls will include workgroup updates, outlining how participants can submit their updates. An example update was shared from Hanshous’s MENA group.

See [Intersect June update - MENA Townhall](https://youtu.be/VQK_lQAyPo4?si=OJ1-YGhq8K1-8w7p) for more
Funded by Intersect until December 2024

Useful links from the MENA group:
[Cardano Forum full Transcription](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbEstM21TRDZwWEpBNXl0Q0k3LVBNU25UREpsUXxBQ3Jtc0tsTUJDbWhoa3plMkRFczVCWmtZbnpIbEEtcTNBM3k3YTgtSkRCUlUxOUtwS2d6U2JXclV6ZHl3U0EtZzAtNl9fUUQzWTFnZFRGVmx1ejlwejRNeDAtSGJFOVhjc0xRanMzZ0MycGtIZzcwcmlSaG5waw&q=https%3A%2F%2Fforum.cardano.org%2Ft%2Fintersect-june-update-mena-townhall%2F133037&v=VQK_lQAyPo4) 
[Whatsapp Cardano MENA Governance related Group](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbmRXVDlhblQycFhaY1VKaTdkUTdlMXRIQlBrZ3xBQ3Jtc0ttN1E4TTRqdHNfaXlIekU3MDMtbFFWaVd4QzJBZ1JuTWRKMnZjc2tJQ1VyMUd2WUtPR3lkUXByYkdTLWNoN1ZpejIwemhLd2NTOWJyQlpaRkRWaEZyeWxCQlFxbUJoUjJWZ3h5dEZlSzZBSC0tZGJNdw&q=https%3A%2F%2Fchat.whatsapp.com%2FFnIMQsTHCpf6bDdkgIezPN&v=VQK_lQAyPo4) 
[Whatsapp Cardano MENA Group](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqazhzMjB2d09rZjFzblEtU2hLMHRGRzNpTmpIQXxBQ3Jtc0tuN295TzU2bGk4RHhKQm82cEQ4ODJHRkp6UEZEMFc1RTNhN3I2bnJER1dUMzRRaTFvRmx5a3RLZXRVMnJCRFhxV2dRV0JKaTJvUnVZSl9KNFZhTi1GUUxBQWEtdHc1SXpPNWN1YlRRZHo4VHBGdmZiWQ&q=https%3A%2F%2Fchat.whatsapp.com%2FLqOl6DwBES5G3CcgSXlAPN&v=VQK_lQAyPo4)

- This months Town Hall included Governance Transparency SIG and Marketing WG updates.

Governance Transparency SIG is a group who is looking to create more spaces to review Cardano Governance who recently worked on reviewing groups' purposes and statements. Join the discussions in #sig-gov-transparency Discord channel to help deliver on their aim

Marketing Workgroup is here to promote and amplify value proposition of the Cardano Ecosystem who recently into what different groups want to accomplish and who are the target audiences. Currently workgroup is looking help with leadership to establish the Working Group officially. Here is a guide how to create Working Groups in Intersect: https://bit.ly/3VCx5nG

- Lara shared updates on Intersect Discord changes, special focus on the new Announcements channels and its structure.
[links to more info?]

- Nagatoshi shared updates on Community Hubs
[links to more info?]

- Updates on the formation of the idea on Special Interest Groups (SIG)

SIG is a Self-assembled member-led initiative that maximizes connections on similar interests and discussions

These groups can organize to become workgroups to increase collective capacity for accountability distribution

As a final agenda item, we tried a social experiment pairing each person into different breakout rooms (15 in our case) and have them quickly share something about themselves in the next 5 minutes.

Once all was over we captured feedback and opened up the breakout room for Constitution discussions. Our main learnings were:

- Invite and coordinate with committees to provide them slots in Town Hall
- When doing the human interfacing experiment again increase the amount of participants in room to 4, incase people drop off or are afk

Breakout Room - Interim Constitution

The conversation in the Interim Constitution Breakout Room was a lively conversation which covered quite a wide range of topics. Participants asked questions from SPOs, to dReps to CIP1694 to the Constitution itself. The mix between well and less informed individuals on Cardano Governance gives a great space where knowledge and information can be effectively shared amongst contributors. Special shoutout to Thomas Lindseth who provided valuable insights and facilitation of the room's discussion.

**Comment by stephen-rowan** [comment]
## Tracking

### Set up Intersect TH problem board 
- [x] Set up Intersect TH Board - https://github.com/orgs/Catalyst-Swarm/projects/2/views/1
- [ ] Tweak design from team input
